
const HISTORY_SEARCH = "HISTORY_SEARCH"

const HISTORY_SEARCH_ARTICLE = 'HISTORY_SEARCH_ARTICLE'

const HISTORY_SEARCH_MUSIC = 'HISTORY_SEARCH_MUSIC'

const HISTORY_SEARCH_VIDEO_COLLECTION = 'HISTORY_SEARCH_VIDEO_COLLECTION'

const HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO = 'HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO'

const HISTORY_SEARCH_GALLERY = 'HISTORY_SEARCH_GALLERY'

const HISTORY_SEARCH_GALLERY_PHOTO = 'HISTORY_SEARCH_GALLERY_PHOTO'

export {
    HISTORY_SEARCH,
    HISTORY_SEARCH_ARTICLE,
    HISTORY_SEARCH_MUSIC,
    HISTORY_SEARCH_VIDEO_COLLECTION,
    HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO,
    HISTORY_SEARCH_GALLERY,
    HISTORY_SEARCH_GALLERY_PHOTO
}