const WELCOME_CACHE_DATA = "WELCOME_CACHE_DATA"

const HISTORY_SEARCH = "HISTORY_SEARCH"

const HISTORY_SEARCH_ARTICLE = 'HISTORY_SEARCH_ARTICLE'

const HISTORY_SEARCH_MUSIC = 'HISTORY_SEARCH_MUSIC'

const HISTORY_SEARCH_MUSIC_SONG = 'HISTORY_SEARCH_MUSIC_SONG'

const HISTORY_SEARCH_VIDEO_COLLECTION = 'HISTORY_SEARCH_VIDEO_COLLECTION'

const HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO = 'HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO'

const HISTORY_SEARCH_GALLERY = 'HISTORY_SEARCH_GALLERY'

const HISTORY_SEARCH_GALLERY_PHOTO = 'HISTORY_SEARCH_GALLERY_PHOTO'

const HISTORY_SEARCH_PUBLIC_WELFARE = 'HISTORY_SEARCH_PUBLIC_WELFARE'

const CACHE_USER_COVER_VALID_HOURS = 'CACHE_USER_COVER_VALID_HOURS'

const CACHE_USER_SHOW_AD = 'CACHE_USER_SHOW_AD'

const USER_ARTICLE = 'USER_ARTICLE'

const USER_MUSIC = 'USER_MUSIC'

const USER_VIDEO = 'USER_VIDEO'

const USER_PHOTO = 'USER_PHOTO'

const USER_ADMIRATION = 'USER_ADMIRATION'

const USER_PUBLIC_WELFARE = 'USER_PUBLIC_WELFARE'

const USER_SHOW_AD = 'USER_SHOW_AD'

const USER_MINI_PROGRAM_COVER = 'USER_MINI_PROGRAM_COVER'

const USER_CLEAR_STORAGE = 'USER_CLEAR_STORAGE'

const USER_COVER_CACHE_VALID_HOURS = 'USER_COVER_CACHE_VALID_HOURS'

const USER_FEED_BACK = 'USER_FEED_BACK'

const USER_ABOUT = 'USER_ABOUT'

const USER_SETTINGS = 'USER_SETTINGS'

const USER_SHOW_CONFIRM_ONCE = 'USER_SHOW_CONFIRM_ONCE'

const USER_SHOW_PUBLIC_WELFARE_ONCE = 'USER_SHOW_PUBLIC_WELFARE_ONCE'

const PAGE_SIZE = 10

const COVER_CACHE_VALID_HOURS = 4

export {
  WELCOME_CACHE_DATA,
  HISTORY_SEARCH,
  HISTORY_SEARCH_ARTICLE,
  HISTORY_SEARCH_MUSIC,
  HISTORY_SEARCH_MUSIC_SONG,
  HISTORY_SEARCH_VIDEO_COLLECTION,
  HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO,
  HISTORY_SEARCH_GALLERY,
  HISTORY_SEARCH_GALLERY_PHOTO,
  HISTORY_SEARCH_PUBLIC_WELFARE,
  CACHE_USER_COVER_VALID_HOURS,
  CACHE_USER_SHOW_AD,

  USER_ARTICLE,
  USER_MUSIC,
  USER_VIDEO,
  USER_PHOTO,
  USER_ADMIRATION,
  USER_PUBLIC_WELFARE,
  USER_SHOW_AD,
  USER_MINI_PROGRAM_COVER,
  USER_CLEAR_STORAGE,
  USER_COVER_CACHE_VALID_HOURS,
  USER_FEED_BACK,
  USER_ABOUT,
  USER_SETTINGS,

  USER_SHOW_CONFIRM_ONCE,
  USER_SHOW_PUBLIC_WELFARE_ONCE,

  PAGE_SIZE,
  COVER_CACHE_VALID_HOURS
}
