const HISTORY_SEARCH = "HISTORY_SEARCH"

const HISTORY_SEARCH_ARTICLE = 'HISTORY_SEARCH_ARTICLE'

const HISTORY_SEARCH_MUSIC = 'HISTORY_SEARCH_MUSIC'

const HISTORY_SEARCH_MUSIC_SONG = 'HISTORY_SEARCH_MUSIC_SONG'

const HISTORY_SEARCH_VIDEO_COLLECTION = 'HISTORY_SEARCH_VIDEO_COLLECTION'

const HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO = 'HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO'

const HISTORY_SEARCH_GALLERY = 'HISTORY_SEARCH_GALLERY'

const HISTORY_SEARCH_GALLERY_PHOTO = 'HISTORY_SEARCH_GALLERY_PHOTO'

const MORE_ARTICLE = 'MORE_ARTICLE'

const MORE_MUSIC = 'MORE_MUSIC'

const MORE_VIDEO = 'MORE_VIDEO'

const MORE_PHOTO = 'MORE_PHOTO'

const MORE_ADMIRATION = 'MORE_ADMIRATION'

const MORE_ABOUT = 'MORE_ABOUT'

const MORE_SHOW_CONFIRM_ONCE = 'MORE_SHOW_CONFIRM_ONCE'

const PAGE_SIZE = 10

export {
  HISTORY_SEARCH,
  HISTORY_SEARCH_ARTICLE,
  HISTORY_SEARCH_MUSIC,
  HISTORY_SEARCH_MUSIC_SONG,
  HISTORY_SEARCH_VIDEO_COLLECTION,
  HISTORY_SEARCH_VIDEO_COLLECTION_VIDEO,
  HISTORY_SEARCH_GALLERY,
  HISTORY_SEARCH_GALLERY_PHOTO,

  MORE_ARTICLE,
  MORE_MUSIC,
  MORE_VIDEO,
  MORE_PHOTO,
  MORE_ADMIRATION,
  MORE_ABOUT,

  MORE_SHOW_CONFIRM_ONCE,

  PAGE_SIZE
}